#!/bin/bash

BASE_DIR=$HOME
echo "Base DIR: $BASE_DIR"

os=`lsb_release -d`;
os='osx'
if [[ $os =~ .*Ubuntu* ]]
then
  os='ubuntu'
else
  os='osx'
fi
echo "Running $os"

for f in "./$os.config/*.sh";
do
  bash $f
done

ln -s $BASE_DIR/dotfiles/tmux.config/tmux.conf $BASE_DIR/.tmux.conf
# Install neovim config
mkdir -p $BASE_DIR/.config
ln -s $BASE_DIR/dotfiles/nvim.config $BASE_DIR/.config/nvim
ln -s $BASE_DIR/dotfiles/nvim.config $BASE_DIR/.vim 

vim +PlugInstall +qall

cd $BASE_DIR

echo "source $BASE_DIR/bash.config/main.sh" > ~/.zshrc
