#!/bin/bash
BASE_DIR=$HOME

echo "Base DIR: $BASE_DIR"

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

sh ./osx.config/brew.sh
sh ./osx.config/osx.sh

ln -s $BASE_DIR/vim.config/vim $HOME/.vim
ln -s $BASE_DIR/tmux.config/tmux.conf $HOME/.tmux.conf

# Install neovim config
mkdir $BASE_DIR/.config
ln -s $BASE_DIR/dotfiles/nvim.config $BASE_DIR/.config/nvim
ln -s $BASE_DIR/dotfiles/nvim.config $BASE_DIR/.vim 

vim +PlugInstall +qall

cd $BASE_DIR

echo "Put 'source $BASE_DIR/bash.config/main.sh' in .zshrc"
